### ISSUE TITLE
 can you offer the code?

### ISSUE THREAD

**Issue by YAwei666** [capuzz/3D-FasterRCNN#1]

**Comment by YAwei666** [comment]
can you offer the code?

**Comment by capuzz** [comment]
Hi. I will write you in pvt. 
Give me your email please.

**Comment by YAwei666** [comment]
yawei992120@foxmail.com，thank you very much

**Comment by JuliaChae** [comment]
Hi, could I also see the code please? julia.chae2000@gmail.com thank you so much

**Comment by capuzz** [comment]
Hi. I am sending you the explanation about the github project.

Write me if you have more questions.

I closed the issue on github.


________________________________
Da: JuliaChae <notifications@github.com>
Inviato: martedì 16 luglio 2019 19:56
A: capuzz/3D-FasterRCNN <3D-FasterRCNN@noreply.github.com>
Cc: capuzz <alessandro.capasso@outlook.com>; Comment <comment@noreply.github.com>
Oggetto: Re: [capuzz/3D-FasterRCNN] can you offer the code? (#1)


Hi, could I also see the code please? julia.chae2000@gmail.com<mailto:julia.chae2000@gmail.com> thank you so much
