### ISSUE TITLE
Is there any code to share?

### ISSUE THREAD

**Issue by lxycopper** [capuzz/3D-FasterRCNN#2]
Hello capuzz,
I am currently doing research on Monocular 3D Object Detection. And I saw you have done a great job in your result, could you please share the code?

**Comment by capuzz** [comment]
I'm sorry I can't share the code but if you want I could give you a ppt file with a detailed explanation of the algorithm. If you are interested send me your email.
Thanks

**Comment by lxycopper** [comment]
Okay, I want that ppt file. Thanks for your generous support!

**Comment by lxycopper** [comment]
My email is lxycopper@gmail.com, thank you very much!
