### ISSUE TITLE
code

### ISSUE THREAD

**Issue by liulingfeng123** [capuzz/3D-FasterRCNN#3]
Hello, I would like to ask when your code is open source？

**Comment by capuzz** [comment]
No, I'm sorry. It is not open source. If you need some advice on the algorithm, I could provide you a pdf file with the explanation of my implementation. 
Let me know if it could be helpful.

**Comment by liulingfeng123** [comment]
Thank you for your reply, this is my email: 1104179308@qq.com. I hope to receive your documents




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "capuzz/3D-FasterRCNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 晚上6:30
收件人:&nbsp;"capuzz/3D-FasterRCNN"<3D-FasterRCNN@noreply.github.com&gt;;
抄送:&nbsp;"刘凌风"<1104179308@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [capuzz/3D-FasterRCNN] code (#3)





 
No, I'm sorry. It is not open source. If you need some advice on the algorithm, I could provide you a pdf file with the explanation of my implementation.
 Let me know if it could be helpful.
